-- +migrate Up
CREATE TABLE IF NOT EXISTS orders (
    order_id VARCHAR(64) PRIMARY KEY,
    exchange VARCHAR(64) NOT NULL,
    symbol VARCHAR(20) NOT NULL,
    side VARCHAR(10) NOT NULL,
    entry_price DOUBLE PRECISION NOT NULL,
    sl DOUBLE PRECISION,
    tp DOUBLE PRECISION,
    qty DOUBLE PRECISION NOT NULL,
    reason TEXT
);
